apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-cart
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: ms-cart
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 40